import type { Currency } from '@shared/types';

export const DEFAULT_CURRENCIES: Currency[] = [
  {
    id: '1',
    code: 'USD',
    name: 'US Dollar',
    symbol: '$',
    type: 'fiat',
    exchangeRateToUSD: 1,
    isSystem: true,
  },
  {
    id: '2',
    code: 'EUR',
    name: 'Euro',
    symbol: '\u20ac',
    type: 'fiat',
    exchangeRateToUSD: 1.08,
    isSystem: true,
  },
  {
    id: '3',
    code: 'RUB',
    name: 'Russian Ruble',
    symbol: '\u20bd',
    type: 'fiat',
    exchangeRateToUSD: 0.011,
    isSystem: true,
  },
  {
    id: '4',
    code: 'BTC',
    name: 'Bitcoin',
    symbol: '\u20bf',
    type: 'crypto',
    exchangeRateToUSD: 60000,
    isSystem: true,
  },
  {
    id: '5',
    code: 'ETH',
    name: 'Ethereum',
    symbol: '\u039e',
    type: 'crypto',
    exchangeRateToUSD: 3000,
    isSystem: true,
  },
  {
    id: '6',
    code: 'USDT',
    name: 'Tether',
    symbol: '\u20ae',
    type: 'stablecoin',
    exchangeRateToUSD: 1,
    isSystem: true,
  },
];
